### ISSUE TITLE
Allow to push tags one by one to overcome GitHub limit

### ISSUE THREAD

**Issue by StarpTech** [lerna-lite/lerna-lite#701]
### Clear and concise description of the problem

Hi, I run into a weird limitation. Github workflows aren't triggered when more than 3 tags are pushed simultaneously. This becomes relevant in `independent` mode. See here for more context https://github.com/lerna/lerna/issues/2218. I first wanted to use `--no-follow-tags` but it doesn't exist in lerna-lite. `--no-push` also has no impact on pushing tags. https://github.com/lerna-lite/lerna-lite/blob/3e7dcb7fcc9bb5d56b57141f23572a67b8e3b073/packages/version/src/version-command.ts#L840

I tested https://github.com/lerna/lerna/issues/2218#issuecomment-1662185323 which unfortunately doesn't work :disappointed:

### Suggested solution

Introduce a new field `--push-tags-serial` to prevent pushing all tags simultaneously.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
PR would be welcome since I'm not sure how I could implement this myself, have you tried with [`--concurrency`](https://github.com/lerna-lite/lerna-lite/wiki/Lerna-Global-Options#--concurrency)?

**Comment by StarpTech** [comment]
I think [--concurrency](https://github.com/lerna-lite/lerna-lite/wiki/Lerna-Global-Options#--concurrency) will have no effect on how git tags are pushed. A potential fix is to push tags in serial as in https://github.com/lerna/lerna/issues/2218#issuecomment-771876933

**Comment by ghiscoding** [comment]
not sure how to implement this in code, I'm on windows and not sure how to transform that linux script into code in Lerna-Lite itself

**Comment by ghiscoding** [comment]
> I first wanted to use `--no-follow-tags` but it doesn't exist in lerna-lite. `--no-push` also has no impact on pushing tags.

it seems that the code always use `--follow-tags`, there could be an option to disable it? I rarely write Git commands, so I can't understand that question but would that help or not?

https://github.com/lerna-lite/lerna-lite/blob/65f81bbc848529550824c7d1a802adaa6095280c/packages/version/src/lib/git-push.ts#L12

I'm not sure how else to help with this problem, have you tried the proposed bash shell script? It's not really an option to convert it to code though since that wouldn't work on Windows but it would certainly works for GitHub users

**Comment by ghiscoding** [comment]
> I first wanted to use `--no-follow-tags` but it doesn't exist in lerna-lite. `--no-push` also has no impact on pushing tags.

@StarpTech I'm still unsure what to do with this issue, if you wanted the `--no-follow-tags` then I could definitely add a new lerna version option for that if you think that would help? Because the default git push command does include `follow-tags` and also `atomic` as can be seen below for the git push

https://github.com/lerna-lite/lerna-lite/blob/5a70501a9bdbaadaa6e54d029c377e26bd17029f/packages/version/src/lib/git-push.ts#L9-L12

Let me know if a new `lerna version --no-follow-tags` could help, I can work on that. Thanks

**Comment by StarpTech** [comment]
We have worked around this by triggering workflows manually in a postversion hook. Far from ideal but it works. Would be great if we would find a solution to this.

**Comment by ghiscoding** [comment]
If you think of any ways to fix it, then please let me know, otherwise I have no idea on how to address this problem

**Comment by StarpTech** [comment]
I'll try to reproduce it on a public repo and send you the link. Maybe we can find a solution to make it work.

**Comment by ghiscoding** [comment]
@StarpTech I just saw this new Lerna PR [Enable throttling when publishing modules](https://github.com/lerna/lerna/pull/4013) that might help with your issue. I might try to implement it in here if it's doable, it should be ok to replicate since I don't see any Nx specific code. So anyway, I assume it is related to your issue

**Comment by StarpTech** [comment]
Hi @ghiscoding publishing NPM wasn't an issue. We run into a GitHub issue where it is not allowed to push more than 3 tags at the same time.

**Comment by StarpTech** [comment]
Check this out https://github.com/travis-ci/docs-travis-ci-com/issues/763#issuecomment-489647446

**Comment by ghiscoding** [comment]
@StarpTech  I'm trying something in PR #871 but I have no idea is that solution is good or not, need feedback
