### ISSUE TITLE
skipBumpOnlyRelease: true does not work

### ISSUE THREAD

**Issue by StarpTech** [lerna-lite/lerna-lite#703]
### Describe the bug

We use `"skipBumpOnlyRelease": true` in `lerna.json` but we see bump-only releases.

```
diff --git a/controlplane/CHANGELOG.md b/controlplane/CHANGELOG.md
index 4530dd7..40594ac 100644
--- a/controlplane/CHANGELOG.md
+++ b/controlplane/CHANGELOG.md
@@ -4,6 +4,10 @@ Images can be found [here](https://github.com/orgs/wundergraph/packages?repo_nam
 All notable changes to this project will be documented in this file.
 See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
 
+## [0.6.2](https://github.com/wundergraph/cosmo/compare/controlplane@0.6.1...controlplane@0.6.2) (2023-08-29)
+
+**Note:** Version bump only for package controlplane
+
 ## [0.6.1](https://github.com/wundergraph/cosmo/compare/controlplane@0.6.0...controlplane@0.6.1) (2023-08-29)
```

### Reproduction

```json
{
  "$schema": "node_modules/@lerna-lite/cli/schemas/lerna-schema.json",
  "version": "independent",
  "command": {
    "publish": {
      "registry": "https://registry.npmjs.org"
    },
    "version": {
      "conventionalCommits": true,
      "createRelease": "github",
      "syncWorkspaceLock": true,
      "changelogIncludeCommitsClientLogin": " (@%l)",
      "skipBumpOnlyRelease": true,
      "message": "chore(release): Publish [skip ci]",
      "changelogHeaderMessage": "Images can be found [here](https://github.com/orgs/wundergraph/packages?repo_name=cosmo)"
    }
  },
  "packages": [
    "cli",
    "controlplane"
  ],
  "npmClient": "pnpm",
  "loglevel": "verbose"
}

```

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

### Environment Info

```
    "@commitlint/cli": "17.6.6",
    "@commitlint/config-conventional": "17.6.6",
    "@lerna-lite/cli": "2.5.0",
    "@lerna-lite/publish": "2.5.0",
    "@lerna-lite/version": "2.5.0",
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/lerna-lite/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lerna-lite/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
This option was added to avoid creating too many releases on GitHub in `independent` mode, but it will still update the `changelog.md` with the regular text entry "Version bump only for package". I added this option mainly because of this other project [Discussion](https://github.com/react-navigation/react-navigation/discussions/11093), though I am not using this option myself since I am not using `independent` mode

**Comment by StarpTech** [comment]
Oh I mean we see real Github Releases not just README updates. Sry for the confusion.

**Comment by ghiscoding** [comment]
hmm I'll have to take another look at this, I had no feedback from that other user and I had no way of testing it apart from unit tests and you're probably the first user who's really trying it in a real project. I'll review it sometime this week, just catching up on all messages since coming back from vacation

**Comment by StarpTech** [comment]
@ghiscoding thank you! Welcome back :smile:

**Comment by ghiscoding** [comment]
@StarpTech was that really done with Lerna-Lite v2.5.0? I still see `"@lerna-lite/cli": "1.12.0",` in your [wundergraph](https://github.com/wundergraph/wundergraph/blob/main/package.json#L77) project and this ship option was added in v2, or was that run manually in dry-run?

**Comment by StarpTech** [comment]
We use the old version in wundergraph but the latest on a private project.

**Comment by ghiscoding** [comment]
hmm the code looks ok to me

https://github.com/lerna-lite/lerna-lite/blob/3ad8d354044dd2e61a80292c1befc90538fcb623/packages/version/src/lib/create-release.ts#L38-L40

and the unit tests are working fine too

https://github.com/lerna-lite/lerna-lite/blob/3ad8d354044dd2e61a80292c1befc90538fcb623/packages/version/src/__tests__/version-create-release.spec.ts#L290-L321

it would help to either have a working project I can test with or if you can add breakpoint or console log in Lerna-Lite's code for the condition check shown above

**Comment by StarpTech** [comment]
> Perhaps you can give it a try as a CLI argument --skip-bump-only-release instead of lerna.json

Yes, let me observe it on the next release.

**Comment by ghiscoding** [comment]
I have reimplemented the code for this option since the first implementation had wrong assumptions on changelog entries. This should work better now even if I still couldn't test it 100% since I don't have any projects with `independent` mode. Give it a try and let me know if it works. 

Also note that I renamed the option to be pluralized (with an "s") `--skip-bump-only-releases` because it better represents the fact that this option can skip multiple releases in independent mode, the singular name still works for now but will be removed in the next major.
