### ISSUE TITLE
Support `--generateReleaseNotes` for GitHub releases

### ISSUE THREAD

**Issue by Kikobeats** [lerna-lite/lerna-lite#793]
### Clear and concise description of the problem

Hello,

GitHub supports auto-generate release body passing `generate_release_notes: true` flag:
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release

The value needs to be passed down from `lerna publish` to `lerna version`, something in this way:

```
lerna version --generateReleaseNotes
```

To support it, just need to pass it here:

https://github.com/lerna-lite/lerna-lite/blob/7e4dce11c6b009dc2848a16858933ff34cd46af0/packages/version/src/lib/create-release.ts#L60

### Suggested solution

I would to see support for it. The output generated by GitHub includes GitHub PRs links and user mentions, that is really helpful to keep contributors in the loop.

Also, it places nice with other flags, like `--conventional-commits`.

Probably it can be accommodated in a way that the current generation of the body can be skipped, since GitHub is already generating it for you. That will lerna even a bit faster.

### Additional context

I have no idea if GitLab supports something similar in order to have 1:1 parity.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
It's already supported but with a different option name [--create-release-discussion-name](https://github.com/lerna-lite/lerna-lite/tree/main/packages/version#--create-release-discussion-name) for GitHub only, also note that you always need to provide a Discussion group name (it cannot be null). I used the flag a few times but stopped since v3, you can take a look at the last one Discussion that it created, [v2.6.0](https://github.com/lerna-lite/lerna-lite/discussions/744)

**Comment by Kikobeats** [comment]
I don't see how is that the same 🤔 

`generate_release_notes` will generate the the body content of the release, also the source code is not passing that value to GitHub REST API.

**Comment by ghiscoding** [comment]
So I might have misunderstood then, can you provide a demo? This looks like `lerna version --conventional-commits --create-release github` to me, why don't you use that?

**Comment by Kikobeats** [comment]
It's about the content of the release is auto-generated by GitHub:

> generate_release_notes: Whether to automatically generate the name and body for this release. If name is specified, the specified name will be used; otherwise, a name will be automatically generated. If body is specified, the body will be pre-pended to the automatically generated notes.

Essentially it's the same than clicking this button in the UI

![CleanShot 2024-01-02 at 18 40 32@2x](https://github.com/lerna-lite/lerna-lite/assets/2096101/d216f766-655c-43bd-890e-661185c1a48c)

**Comment by ghiscoding** [comment]
Ok then a contribution would be welcome, I don't have time to look at this and it would be nice to receive contributions. You can take a look at how I've implemented the Create Discussion (from this PR #604), which I've talked earlier and it might be helpful to know which file to change for this new option and I assume this option will have to be in `lerna version` as well

**Comment by ghiscoding** [comment]
Actually I added something similar which might do what you want, when the `GH_TOKEN` is not provided, I use [new-github-release-url](https://www.npmjs.com/package/new-github-release-url) to create a release via the GitHub Release form, I took the same approach as the [release-it](https://github.com/release-it/release-it/blob/main/docs/github-releases.md), perhaps we could just add a flag for it instead of just checking the tokens, in `release-it` they have this option to override automation and make it manual
> Set `github.web`: true explicitly to override this `GITHUB_TOKEN` check.

https://github.com/lerna-lite/lerna-lite/blob/7e4dce11c6b009dc2848a16858933ff34cd46af0/packages/version/src/lib/create-release.ts#L44-L58

**Comment by ghiscoding** [comment]
@Kikobeats ok I took another look at this and now understood that since the project already uses Octokit Rest, the only thing needed for this was to add the option `generate_release_notes` when calling the `createRelease` with Octokit. The new option is `lerna version --generate-release-notes` (or `generateReleaseNotes` in `lerna.json` config). 

I enabled the new option and pushed a new release [v3.2.0](https://github.com/lerna-lite/lerna-lite/releases/tag/v3.2.0) to see if it worked and it did. 

However, personally I still prefer the typical conventional changelog approach (with Bug Fixes, Features groups) and will re-enable that option. Also note that last year I added a new option that you might not be aware of which also adds contributors, the option is [`--changelog-include-commits-client-login [msg]`](https://github.com/lerna-lite/lerna-lite/tree/main/packages/version#--changelog-include-commits-client-login-msg) which I have been using directly in Lerna-Lite since I created the option. 

https://github.com/lerna-lite/lerna-lite/blob/0e2c04b69887d4142364c1ea2ff170a8d00a5fa9/lerna.json#L14-L17

For example, this produces 

![image](https://github.com/lerna-lite/lerna-lite/assets/643976/5b6cdb0e-204b-496a-b125-fee1d7106b37)

if we compare this to the new option `lerna version --generate-release-notes`, it does similar output especially for the contributors.

![image](https://github.com/lerna-lite/lerna-lite/assets/643976/c78659de-f6ee-4df0-995b-cabb4fe44d22)

**Comment by ghiscoding** [comment]
Actually I took the approach that you mentioned to let GitHub produce the release notes by itself (without providing `name` and `body`) but considering the output it creates. I wonder if we should add back the `body` from conventional changelog? Perhaps we might need a new option for that? See below for the new approach

https://github.com/lerna-lite/lerna-lite/blob/5a70501a9bdbaadaa6e54d029c377e26bd17029f/packages/version/src/lib/create-release.ts#L77-L84

**Comment by ghiscoding** [comment]
@Kikobeats it would be nice to have confirmation that it works...
