### ISSUE TITLE
OTP failures: Npm package not released but tag created

### ISSUE THREAD

**Issue by farfromrefug** [lerna-lite/lerna-lite#850]
### Describe the bug

If the npm OTP fails (pasted the OTP code too late when it was not valid anymore) then the NPM package is not published but the tag on git is already created. Same thing for the github release which is already created

### Expectation

I would expect no release to be made on npm/git/github

### Reproduction

create a new release with lerna publish and enter unvalid OTP code

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

### Environment Info

System:
    OS: macOS 14.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 6.02 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 4.0.2 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    Watchman: 2024.01.22.00 - /usr/local/bin/watchman

### Used Package Manager

yarn >= 2.x

### Validations

- [X] Follow our [Code of Conduct](https://github.com/lerna-lite/lerna-lite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/lerna-lite/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/lerna-lite/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/lerna-lite/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by farfromrefug** [comment]
@ghiscoding  btw while this happened it broke my package.json again as explained here https://github.com/lerna-lite/lerna-lite/issues/813. Though i am using latest version

**Comment by ghiscoding** [comment]
> EDIT: and it did again when i CTRL-C while asked for OTP

That is normal since the process is to temporarily change the actual `package.json`, publish it, and then replace the file content with the original package. However when you do the Ctrl+C in the middle of that process, well Yes you end up with a broken `package.json` because you did not let it finish its execution. That process is also the same when using `workspace:` protocol. 

I don't think there's anything I can do to address this though because that would probably require reimplementing the entire thing which I don't want to do, neither have time to do. Part of your concerns were asked long time ago in this Lerna [issue](https://github.com/lerna/lerna/issues/1767)

There are new code in place that will allow you to resume a publish if it failed before it had time to finish its publishing process (for example when you lose internet connection or your OTP is no longer valid). This was discussed in #413 and provided via PR #469 (which itself came from this original Lerna [PR 3513](https://github.com/lerna/lerna/pull/3513). However this assumes that your `package.json` isn't in an invalid state.

To avoid such issue, I never use an OTP that has just a few seconds left, I always wait for the next 30sec cycle and then use that new OTP. But even better now, I use GitHub workflow to publish and I never had any problems since I use those, this is also the only way to sign an npm publish with `--provenance`. I also wrote an article explaining how to this [How to publish on npm with `--provenance` using Lerna-Lite](https://dev.to/ghiscoding/how-to-publish-on-npm-with-provenance-using-lerna-lite-3cjf)

https://github.com/lerna-lite/lerna-lite/blob/main/.github/workflows/publish-npm-latest.yml

**Comment by ghiscoding** [comment]
If you're not happy with the answer, I would suggest you contribute back to the project. My main goal with this fork is simply to keep it up to date and without any Nx related stuff that the new Lerna has.

**Comment by farfromrefug** [comment]
@ghiscoding you should be able to catch CTRL-C to close gracefully while resetting the package.json https://stackoverflow.com/questions/20165605/detecting-ctrlc-in-node-js

IT is not that i am not satisfied with the answer. I am reporting issues that s all. The issue with tag  being created is not the biggest of deals, i can live with that.
The issue with the broken package.json is much more dangerous. The reason is that it removes the `scripts` field. If i then run `lerna publish` again then i publish an empty package because there is not a `build` script anymore(happened that afternoon).
This would also happen with github action release. And i dont do github action releases. I prefer to do by hand so that i can check it all. Plus it is a lot more environment friendly.
So i am ok with you closing this issue. But i hope the package.json broken issue to find a fix one day. If i can contribute i can. Tbh just like you i have my hands full with open source projects.

Finally really dont worry i dont mind you closing that issue. (btw for the otp i realized i actually pasted an otp for github and not npm ...)

**Comment by ghiscoding** [comment]
> The issue with the broken package.json is much more dangerous. The reason is that it removes the `scripts` field. If i then run `lerna publish` again then i publish an empty package because there is not a `build` script anymore(happened that afternoon).

You are the only person who reported this problem (twice), I never had this problem on my side. If it happened more than once then I would suggest you remove the `scripts` deletion. Because like I said, it's a temporary change and there's no transactions of any kind to rollback and implementing a temp copy of `package.json` would probably require a lot of code change which I don't have time to do because like you my plate is already full with open source project which doesn't put any bread on my table. 

I know modifying the `package.json` and leaving it in an invalid state is not ideal and I'll keep that in mind, but at this point, I don't have time to look into this and don't know how to do it without too much refactoring. It doesn't seem to happen very often either.

**Comment by farfromrefug** [comment]
@ghiscoding yes i will remove the scripts deletion. seems much safer for now.

**Comment by ghiscoding** [comment]
perhaps what I could do at the moment is to add a Note in the description of that option mentioning that since it modifies the actual package and there's no rollback at the moment

**Comment by farfromrefug** [comment]
> perhaps what I could do at the moment is to add a Note in the description of that option mentioning that since it modifies the actual package and there's no rollback at the moment

Might be a good safeguard

**Comment by ghiscoding** [comment]
This is issue is a bit old but I wanted to share that I made some improvements that should avoid falling into these issues in the future
- PR #1034 

Also if your release failing in the middle, you can simply recall `lerna publish` and it will resume were it previously failed, that was an improvement made a long time ago in PR #469  "recover from network failure"

So there should always be a viable fix to resume a half shipped release.

**Comment by farfromrefug** [comment]
@ghiscoding awesome. Thank you so much
